name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get Firefox
      run: wget https://archive.mozilla.org/pub/firefox/candidates/72.0b2-candidates/build1/linux-x86_64/en-US/firefox-72.0b2.tar.bz2
    - name: Extract Firefox
      run: tar xjf firefox-72.0b2.tar.bz2
    - name: Get Firefox Driver
      run: wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
    - name: Extract firefox driver
      run: tar xzf geckodriver-v0.26.0-linux64.tar.gz
    - name: Copy geckodriver to firefox
      run: cp geckodriver firefox
    - name: repack firefox
      run: cd firefox; tar -cvf ../firefoxbundle.tar.bz2 *
    - name: Get the AWS Wagon
      run: wget https://repo1.maven.org/maven2/org/springframework/build/aws-maven/5.0.0.RELEASE/aws-maven-5.0.0.RELEASE.jar
    - name: Copy aws-maven
      run: cp aws-maven-5.0.0.RELEASE.jar $MAVEN_HOME/lib
    - name: deploy file
      run: >
        mvn deploy:deploy-file
        -Dfile=firefox.zip
        -DgroupId=com.octopus.linux
        -DartifactId=firefoxbundle
        -Dversion=72.0
        -Dpackaging=tar.bz2
        -DrepositoryId=octopus-maven-repo
        -Durl=s3://octopus-maven-repo/release