name: Build Chrome Windows Bundle
on: [push]
jobs:
  build:
    env:
      AWS_SECRET_KEY:  ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
      VERSION: 78.0
      BROWSER: https://github.com/macchrome/winchrome/releases/download/v78.0.3904.108-r693954-Win64/ungoogled-chromium-78.0.3904.108-1_windows.7z
      DRIVER: https://chromedriver.storage.googleapis.com/78.0.3904.105/chromedriver_win32.zip
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./buildchrome.sh