name: Build FIrefox Bundle
on: [push]
jobs:
  build:
    env:
      AWS_SECRET_KEY:  ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./buildfirefox.sh