name: Package OpenJDK for Linux
on: [push]
jobs:
  build:
    env:
      AWS_SECRET_KEY:  ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
      VERSION: 13.0.1
      DOWNLOAD: https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_linux-x64_bin.tar.gz
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./openjdklinux.sh